In [1]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)

print("Pandas version:", pd.__version__)

Pandas version: 2.2.2

In [2]:
customers = pd.DataFrame({
    "customer_id": [101, 102, 103, 104, 105],
    "customer_name": ["Ananya", "Bharat", "Charan", "Divya", "Esha"],
    "region": ["South", "North", "South", "West", "East"]
})

orders = pd.DataFrame({
    "order_id": [1, 2, 3, 4, 5, 6],
    "customer_id": [101, 102, 103, 106, 101, 105],
    "product": ["Laptop", "Mouse", "Keyboard", "Monitor", "Keyboard", "Laptop"],
    "sales": [55000, 1200, 2500, 15000, 2700, 60000]
})

display(customers)
display(orders)

   customer_id customer_name region
0          101        Ananya  South
1          102        Bharat  North
2          103        Charan  South
3          104         Divya   West
4          105          Esha   East

   order_id  customer_id   product  sales
0         1          101    Laptop  55000
1         2          102     Mouse   1200
2         3          103  Keyboard   2500
3         4          106   Monitor  15000
4         5          101  Keyboard   2700
5         6          105    Laptop  60000

In [3]:
# Inner Join
inner_merge = pd.merge(
    customers,
    orders,
    on="customer_id",
    how="inner"
)

print("INNER JOIN")
display(inner_merge)


# Left Join
left_merge = pd.merge(
    customers,
    orders,
    on="customer_id",
    how="left"
)

print("LEFT JOIN")
display(left_merge)


# Right Join
right_merge = pd.merge(
    customers,
    orders,
    on="customer_id",
    how="right"
)

print("RIGHT JOIN")
display(right_merge)


# Outer Join
outer_merge = pd.merge(
    customers,
    orders,
    on="customer_id",
    how="outer",
    indicator=True
)

print("OUTER JOIN")
display(outer_merge)

INNER JOIN

   customer_id customer_name region  order_id   product  sales
0          101        Ananya  South         1    Laptop  55000
1          101        Ananya  South         5  Keyboard   2700
2          102        Bharat  North         2     Mouse   1200
3          103        Charan  South         3  Keyboard   2500
4          105          Esha   East         6    Laptop  60000

LEFT JOIN

   customer_id customer_name region  order_id   product    sales
0          101        Ananya  South       1.0    Laptop  55000.0
1          101        Ananya  South       5.0  Keyboard   2700.0
2          102        Bharat  North       2.0     Mouse   1200.0
3          103        Charan  South       3.0  Keyboard   2500.0
4          104         Divya   West       NaN       NaN      NaN
5          105          Esha   East       6.0    Laptop  60000.0

RIGHT JOIN

   customer_id customer_name region  order_id   product  sales
0          101        Ananya  South         1    Laptop  55000
1          102        Bharat  North         2     Mouse   1200
2          103        Charan  South         3  Keyboard   2500
3          106           NaN    NaN         4   Monitor  15000
4          101        Ananya  South         5  Keyboard   2700
5          105          Esha   East         6    Laptop  60000

OUTER JOIN

   customer_id customer_name region  order_id   product    sales      _merge
0          101        Ananya  South       1.0    Laptop  55000.0        both
1          101        Ananya  South       5.0  Keyboard   2700.0        both
2          102        Bharat  North       2.0     Mouse   1200.0        both
3          103        Charan  South       3.0  Keyboard   2500.0        both
4          104         Divya   West       NaN       NaN      NaN   left_only
5          105          Esha   East       6.0    Laptop  60000.0        both
6          106           NaN    NaN       4.0   Monitor  15000.0  right_only

In [4]:
sales_data = pd.DataFrame({
    "region": [
        "South", "South", "North", "North", "West",
        "West", "East", "East", "South", "North"
    ],
    "product": [
        "Laptop", "Mouse", "Laptop", "Keyboard", "Laptop",
        "Mouse", "Keyboard", "Laptop", "Keyboard", "Mouse"
    ],
    "sales": [
        55000, 1200, 65000, 2500, 48000,
        1800, 3000, 52000, 2700, 2200
    ]
})

display(sales_data)

  region   product  sales
0  South    Laptop  55000
1  South     Mouse   1200
2  North    Laptop  65000
3  North  Keyboard   2500
4   West    Laptop  48000
5   West     Mouse   1800
6   East  Keyboard   3000
7   East    Laptop  52000
8  South  Keyboard   2700
9  North     Mouse   2200

In [5]:
sales_pivot = pd.pivot_table(
    sales_data,
    index="region",
    columns="product",
    values="sales",
    aggfunc="sum",
    fill_value=0
)

print("SALES BY REGION AND PRODUCT")

display(sales_pivot)

SALES BY REGION AND PRODUCT

product  Keyboard  Laptop  Mouse
region
East         3000   52000      0
North        2500   65000   2200
South        2700   55000   1200
West            0   48000   1800

In [6]:
region_summary = pd.pivot_table(
    sales_data,
    index="region",
    values="sales",
    aggfunc=["sum", "mean", "count"]
)

print("REGION SUMMARY")

display(region_summary)

REGION SUMMARY

          sum          mean count
        sales         sales sales
region
East    55000  27500.000000     2
North   69700  23233.333333     3
South   58900  19633.333333     3
West    49800  24900.000000     2

In [7]:
region_summary = pd.pivot_table(
    sales_data,
    index="region",
    values="sales",
    aggfunc=["sum", "mean", "count"]
)

print("REGION SUMMARY")

display(region_summary)

REGION SUMMARY

          sum          mean count
        sales         sales sales
region
East    55000  27500.000000     2
North   69700  23233.333333     3
South   58900  19633.333333     3
West    49800  24900.000000     2

In [8]:
wide_data = pd.DataFrame({
    "region": ["South", "North", "West"],
    "Laptop": [55000, 65000, 48000],
    "Mouse": [1200, 2200, 1800],
    "Keyboard": [2700, 2500, 3000]
})

print("WIDE DATA")

display(wide_data)


long_data = pd.melt(
    wide_data,
    id_vars=["region"],
    var_name="product",
    value_name="sales"
)

print("LONG DATA")

display(long_data)

WIDE DATA

  region  Laptop  Mouse  Keyboard
0  South   55000   1200      2700
1  North   65000   2200      2500
2   West   48000   1800      3000

LONG DATA

  region   product  sales
0  South    Laptop  55000
1  North    Laptop  65000
2   West    Laptop  48000
3  South     Mouse   1200
4  North     Mouse   2200
5   West     Mouse   1800
6  South  Keyboard   2700
7  North  Keyboard   2500
8   West  Keyboard   3000

In [9]:
product_summary = (
    sales_data
    .groupby("product", as_index=False)
    .agg(
        total_sales=("sales", "sum"),
        average_sales=("sales", "mean"),
        number_of_orders=("sales", "count")
    )
    .sort_values("total_sales", ascending=False)
)

display(product_summary)

highest_product = product_summary.iloc[0]["product"]
highest_sales = product_summary.iloc[0]["total_sales"]

print("Product with highest sales:", highest_product)
print("Total sales: ₹{:,.2f}".format(highest_sales))

    product  total_sales  average_sales  number_of_orders
1    Laptop       220000   55000.000000                 4
0  Keyboard         8200    2733.333333                 3
2     Mouse         5200    1733.333333                 3

Product with highest sales: Laptop
Total sales: ₹220,000.00

In [10]:
print("WEEK 2 — DAY 2 COMPLETED")

print("✓ Merge — Inner, Left, Right, Outer")
print("✓ Pivot Table")
print("✓ Melt — Wide to Long")
print("✓ Reshape — Long to Wide")
print("✓ Method Chaining")
print("✓ Sales Analysis")

WEEK 2 — DAY 2 COMPLETED
✓ Merge — Inner, Left, Right, Outer
✓ Pivot Table
✓ Melt — Wide to Long
✓ Reshape — Long to Wide
✓ Method Chaining
✓ Sales Analysis